### ISSUE TITLE
@tailwindcss/line-clampで一部表示にしてるが描画がなんかおかしい

### ISSUE THREAD

**Issue by Miura-code** [enpitut2023/kanso_batake#68]
コミットhttps://github.com/enpitut2023/kanso_batake/commit/075dd63037a2e49b92dda16bd386c58dfbd79cd5
`line-clamp-5`で上から5行のみ表示させようとしている。  
上から５行目の最後に`...`が表示されるが、6行目もなんか表示される  
６行目以降は切れてる  
<img width="724" alt="image" src="https://github.com/enpitut2023/kanso_batake/assets/124149163/0850920b-45d3-4cb4-bc44-72231827be48">

**Comment by Miura-code** [comment]
> コミット[075dd63](https://github.com/enpitut2023/kanso_batake/commit/075dd63037a2e49b92dda16bd386c58dfbd79cd5) `line-clamp-5`で上から5行のみ表示させようとしている。 上から５行目の最後に`...`が表示されるが、6行目もなんか表示される ６行目以降は切れてる <img alt="image" width="724" src="https://private-user-images.githubusercontent.com/124149163/296612193-0850920b-45d3-4cb4-bc44-72231827be48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDY5NzcsIm5iZiI6MTcwNTMwNjY3NywicGF0aCI6Ii8xMjQxNDkxNjMvMjk2NjEyMTkzLTA4NTA5MjBiLTQ1ZDMtNGNiNC1iYzQ0LTcyMjMxODI3YmU0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwODE3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2QzNGZmYmFiNGE2MWQ0YTk1MTdmOTIwMmU4NDliOGQ5ZGNmOTRmNmVmYzYyMDA5YzM1ODZiZGIwNGVmNzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MqtbP6so9S9iA-ocfpm12FdzLFWJfesBM6CSpFAwlvU">

**Comment by DoiRyoto** [comment]
考えられるのはline heightの設定とかかな
line heightを小さくすればなんとかなる？かも？

こっちでも調べてみます
